name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm install
      - run: npx prisma generate --schema=./src/database/prisma/schema.prisma
      - run: npx prisma migrate deploy --schema=./src/database/prisma/schema.prisma
      - run: npm run seed
      - run: npm test
